### TEST ROUTE
GET http://localhost:8080/api/v1

### TEST ROUTE
GET http://localhost:8080/api/v1/time

        #-------------------------------------STATES---------------------------------------------------#

### GET STATES
GET http://localhost:8080/api/v1/states

### GET STATE BY ID
GET http://localhost:8080/api/v1/states/24

### CREATE STATE
POST http://localhost:8080/api/v1/states HTTP/1.1
Content-Type: application/json

{
    "name": "UG",
    "code": "200"
}

### UPDATE STATE BY ID
PUT http://localhost:8080/api/v1/states/24  HTTP/1.1
Content-Type: application/json

{
    "name": "Rwanda",
    "code": "126"
}

### DELETE STATE BY ID
DELETE http://localhost:8080/api/v1/states/11


    #-------------------------------------CITY---------------------------------------------------#
### GET CITY 
GET http://localhost:8080/api/v1/cities

### GET CITY BY ID
GET http://localhost:8080/api/v1/cities/8

### CREATE CITY

POST http://localhost:8080/api/v1/cities HTTP/1.1
Content-Type: application/json

{
    "name": "Sotik",
    "state_id": 1 
}

### UPDATE CITY BY ID
PUT http://localhost:8080/api/v1/cities/8 HTTP/1.1
Content-Type: application/json

{
    "name": "kapsabet",	
    "state_id": 1 
}

### DELETE CITY BY ID
DELETE http://localhost:8080/api/v1/cities/11


        #-----------------------------------ADDRESSES---------------------------------------------------#
### GET ALL ADDRESSES
GET http://localhost:8080/api/v1/addresses

### GET ADDRESS BY ID
GET http://localhost:8080/api/v1/addresses/10

### CREATE ADDRESS
POST http://localhost:8080/api/v1/addresses HTTP/1.1
Content-Type: application/json

{
    "street_address_1": "1234 kipchabo",
    "street_address_2": "kombe road",
    "city_id": 1,
    "zip_code": "12890",
    "delivery_instructions": "Deliver to the gate",
    "user_id": 1
}


### UPDATE ADDRESS BY ID
PUT http://localhost:8080/api/v1/addresses/10 HTTP/1.1
Content-Type: application/json

{
    "street_address_1": "1234 kipchabo",
    "street_address_2": "keru road",
    "city_id": 1,
    "zip_code": "2546",
    "delivery_instructions": "Deliver to the field",
    "user_id": 3
}

### DELETE ADDRESS BY ID
DELETE http://localhost:8080/api/v1/addresses/10

        #------------------------------------- Restaurants  ---------------------------------------------------#

### GET ALL RESTAURANTS
GET http://localhost:8080/api/v1/restaurants

### GET RESTAURANT BY ID
GET http://localhost:8080/api/v1/restaurants/1

### CREATE RESTAURANT
POST http://localhost:8080/api/v1/restaurants HTTP/1.1
Content-Type: application/json

{
    "name": "Mama joy",
    "street_address": "1073 kutus",
    "zip_code": "12345",
    "city_id": 1
}

### UPDATE RESTAURANT BY ID
PUT http://localhost:8080/api/v1/restaurants/5 HTTP/1.1
Content-Type: application/json

{
    "name": "Mama Mwende",
    "street_address": "1234 Main St",
    "zip_code": "12345",
    "city_id": 1
}

### DELETE RESTAURANT BY ID
DELETE http://localhost:8080/api/v1/restaurants/6

        #------------------------------------- users  ------------------------------------------------

### GET ALL USERS
GET http://localhost:8080/api/v1/users

### GET USER BY ID
GET http://localhost:8080/api/v1/users/5

### CREATE USER
POST http://localhost:8080/api/v1/users HTTP/1.1
Content-Type: application/json

{
    "name": "Joy Neema",
    "contact_phone": "0712345678",
    "phone_verified": true,
    "email": "Joy@gmail.com",
    "email_verified": true,
    "confirmation_code": "1234",
    "password": "password1"
}

### UPDATE USER BY ID
PUT http://localhost:8080/api/v1/users/5 HTTP/1.1
Content-Type: application/json

{
    "name": "Mercy Chelimo",
    "contact_phone": "0712345678",
    "phone_verified": true,
    "email": "mercy@gmail.com",
    "email_verified": true,
    "confirmation_code": "1234",
    "password": "pass123"
}	

### DELETE USER BY ID
DELETE http://localhost:8080/api/v1/users/5

        #------------------------------------- categories  ------------------------------------------------

### GET ALL CATEGORIES
GET http://localhost:8080/api/v1/categories

### GET CATEGORY BY ID
GET http://localhost:8080/api/v1/categories/5

### CREATE CATEGORY
POST http://localhost:8080/api/v1/categories HTTP/1.1
Content-Type: application/json

{
    "name": "Good luck"
}

### UPDATE CATEGORY BY ID
PUT http://localhost:8080/api/v1/categories/5 HTTP/1.1
Content-Type: application/json

{
    "name": "Good Luck Hotel"
}

### DELETE CATEGORY BY ID
DELETE http://localhost:8080/api/v1/categories/5

        #------------------------------------- products  ------------------------------------------------


