### TEST ROUTE
GET http://localhost:8080/

                #-------------------------------------STATES---------------------------------------------------#

### GET STATES
GET http://localhost:8080/states

### GET STATE BY ID
GET http://localhost:8080/states/22

### CREATE STATE
POST http://localhost:8080/states HTTP/1.1
Content-Type: application/json

{
    "name": "Tanzania",
    "code": "200",
}

### UPDATE STATE BY ID
PUT http://localhost:8080/states/23  HTTP/1.1
Content-Type: application/json

{
    "name": "Rwanda",
    "code": "126"
}

### DELETE STATE BY ID
DELETE http://localhost:8080/states/23


            #-------------------------------------CITY---------------------------------------------------#
### GET CITY 
GET http://localhost:8080/cities

### GET CITY BY ID
GET http://localhost:8080/cities/10

### CREATE CITY

POST http://localhost:8080/cities HTTP/1.1
Content-Type: application/json

{
    "name": "Bomet",
    "state_id": 1 
}

### UPDATE CITY BY ID
PUT http://localhost:8080/cities/10 HTTP/1.1
Content-Type: application/json

{
    "name": "sotik",
    "state_id": 1 
}

### DELETE CITY BY ID
DELETE http://localhost:8080/cities/9


                #-------------------------------------ADDRESSES---------------------------------------------------#
### GET ALL ADDRESSES
GET http://localhost:8080/addresses

### GET ADDRESS BY ID
GET http://localhost:8080/addresses/8

### CREATE ADDRESS
POST http://localhost:8080/addresses HTTP/1.1
Content-Type: application/json

{
    "street_address_1": "1234 nandi",
    "street_address_2": "Kagio road",
    "city_id": 1,
    "zip_code": "12890",
    "delivery_instructions": "Deliver to the gate",
    "user_id": 1
}


### UPDATE ADDRESS BY ID
PUT http://localhost:8080/addresses/7 HTTP/1.1
Content-Type: application/json

{
    "street_address_1": "1234 kipchabo",
    "street_address_2": "keru road",
    "city_id": 1,
    "zip_code": "2546",
    "delivery_instructions": "Deliver to the field",
    "user_id": 3
}

### DELETE ADDRESS BY ID
DELETE http://localhost:8080/addresses/9

                         #-------------------------------------   ---------------------------------------------------#